// Importing required modules
import type { Metadata } from "next";

// Importing the fonts from Google font
import { Poppins } from "next/font/google";

// Importing custom Stylesheet
import "./globals.css";

// Importing custom service provider
import Provider from "./provider";

// Configuring the Poppins font-family
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

// Defining the meta data for SEO purpose
export const metadata: Metadata = {
  title: "Wire Code",
  description: "Generated by create next app",
};

// Defining the Root page layout for our Application
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
};
